language: node_js
node_js:
- 10.14.1
branches:
  only:
  - master
  - "/^[0-9]+.[0-9]+.[0-9]+(-.*)?$/"
  - "/^greenkeeper/.*$/"
after_success: "./node_modules/.bin/codecov"
deploy:
  provider: npm
  on:
    tags: true
    repo: parse-community/parse-server-s3-adapter
  email:
    secure: UuCepGEvvjLpwtPnIqgYPQ3pkU1R7oJg6Izor3qAPFNen6f2IYTsRpQP8/s7VUTQeU/6bzEJ8AvFYTbTCl1mMLwWgQWedf9BcXuPKPuOu6Detodq11yAW+auhizcEbv5TQfskDEzsXPUCd696h+/HRkjYmEJWioSrdXc3vHk1LYvMMO1f9wH08ryR8n3xBYuaIZXa4Jd5vMVzrCJexYT7LiNLRdI/RvGYBMwfSaDb2q6FLdcfss0zC6diD0akYISWVbDFzU05bGWCHxf1zu9trQ+wTZSlvA6KG1ZLInd5C4vemXiXSOPC8veoqR3yZpwMESgLOnIGI5AHgeZvKtF4h8avRK6fSi32v9GBo83QaGbwx6G2lSZKKtbutow1BhLHG++C6OmS4cVT9J7PIicu/mCh+mX1/smTiWkHEjTGG88rF6gzl+epc/BMf8F7DdN9eZ1Cc8/4luO2uhhWGN9S5o0gkmbMYJ3crfPUY6Dbyq5HeKHvy4uVb/fPUl8NTynLSg3UHpNUMjfyseNPOYrxIPY0CShHmBw0ceG6dfSW6MGiEj+SyUGzlYoxH7Cb4dGd0NlW3VRLdVGzLJNJ2Fe3TzqVkwsySg/9/oQjHJZKgvu+uJcY7neqchmnoDMo49QUjv07ARhmXo50vdfXpkyDmHXHj8+0KK1Zjko9FqBL00=
  api_key:
    secure: qUPAVHRZLYQSKTL2Bc/T/CC4SD4sRLRudRolvb7xmL2GYke1Eb19/iyukUlh8J2TybsTxOkSe6k6l676rg0toiVg/zYqvz97kVgSgYB+irKboi4CpAPbXk4CdKU6rVQ5IUVKLbp4uPaYoEfWx1uhcbI7X18o1TqvzYDS3DBNh13txrVJK2RRI30y70NKSYZ8jNTnhvWRa12I5yW7uaFqUdKPzZF0IXAvNoL0+MsQ8Qchi8RLc4UPsu9iYuz3tI65Ho7wQX8udwlGqd7ny9J0OcWHXkPkNaCKP0QqLdglXrgPtOdLy6DwQgpTv5pAmPPI0kp3h6mH8U4RlgkbiG6pMbJ2tJj6kh5Xps3I55jQnlWsFqFUKwCPcvvyADLmoc1MTVxfGGqRA45rreGsbGxIOJtqaC/9ezMLitD2VOBww6hqFYlXvaVau/bYtU13COm6PnBSR2Nx5l+xcfZpzL+MlhhKaFV8kSG1tswxDHSPrdNK7nx4TYratN0F/Em48kIYq+XBjLdfOTCEm8/JnuTsrPfwP0o7Gorl/tjT0Q/qJiv+/i6t0a0goQPra6hJuclKX+ZqXCaXI1usWK1dBJ2HVAX2g5FQTd8uZk+cTv5sUbNPeoYVYMcDaLrh9b7TohX0cZT4WpRfW3ho1Bj/U2IemLp30XR8v8hbMzwM0+sL1YU=
